# Generated by Django 5.1.1 on 2024-09-27 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PestsAndDiseases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Symptoms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(max_length=255)),
                ('pest_disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to='backend_app.pestsanddiseases')),
            ],
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=255)),
                ('pest_disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transmissions', to='backend_app.pestsanddiseases')),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentGuidelines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guideline', models.TextField()),
                ('pest_disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_guidelines', to='backend_app.pestsanddiseases')),
            ],
        ),
    ]
