# Generated by Django 5.1.1 on 2024-10-19 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pestsanddiseases',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pestanddiseases'),
        ),
    ]
